name: Generate docs
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/docs.yml
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p doc
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: nurl
          version: "Neovim >= 0.10.0"
          toc: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate vimdoc"
          file_pattern: doc/*
